// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGfeI6dtXouUxMGYRYbRXoVzbABmrCPm8',
    appId: '1:595532494607:web:a3ce2502d6c41c2d85707a',
    messagingSenderId: '595532494607',
    projectId: 'tale-tailor-404914',
    authDomain: 'tale-tailor-404914.firebaseapp.com',
    storageBucket: 'tale-tailor-404914.appspot.com',
    measurementId: 'G-05M9K8KP25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjMPbLPtS9ujtUPZRRlaqL7Yw4yWuSxY',
    appId: '1:595532494607:android:f88cb1991b61628f85707a',
    messagingSenderId: '595532494607',
    projectId: 'tale-tailor-404914',
    storageBucket: 'tale-tailor-404914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdj3pDVm6zAKgjsDCJxAf0hOm9jYAT28',
    appId: '1:595532494607:ios:d4770f24499f7ade85707a',
    messagingSenderId: '595532494607',
    projectId: 'tale-tailor-404914',
    storageBucket: 'tale-tailor-404914.appspot.com',
    iosBundleId: 'com.example.creativeWritingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdj3pDVm6zAKgjsDCJxAf0hOm9jYAT28',
    appId: '1:595532494607:ios:7bfcf63d60a018c085707a',
    messagingSenderId: '595532494607',
    projectId: 'tale-tailor-404914',
    storageBucket: 'tale-tailor-404914.appspot.com',
    iosBundleId: 'com.example.creativeWritingApp.RunnerTests',
  );
}
